return {
--   "MeanderingProgrammer/render-markdown.nvim",
--   enabled = false,
--   dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-mini/mini.nvim" }, -- if you use the mini.nvim suite
--   -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-mini/mini.icons' }, -- if you use standalone mini plugins
--   -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
--   ---@module 'render-markdown'
--   ---@type render.md.UserConfig
--   opts = {
--     code = {
--       width = "block",
--       min_width = 80,
--       border = "thin",
--       left_pad = 1,
--       right_pad = 1,
--       position = "right",
--       language_icon = true,
--       lanauge_name = true,
--     },
--     anti_conceal = {
--       disabled_modes = { "n" },
--       ignore = {
--         bullet = true,
--         head_border = true,
--         head_background = true,
--       },
--     },
--   },
}
